import type { Metadata } from "next";
import localFont from "next/font/local";
import { Montserrat } from "next/font/google";
import "./globals.css";

// Local font — Forsela
const forselafont = localFont({
  src: "./fonts/Forsela.ttf",
  variable: "--font-forsela",
});
// Local font — Edo
const edofont = localFont({
  src: "./fonts/edo.ttf",
  variable: "--font-edo",
});

// Main font — Montserrat
const montserrat = Montserrat({
  subsets: ["latin"],
  variable: "--font-montserrat",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${montserrat.variable} ${forselafont.variable} ${edofont.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
